baseURL = "https://mijux.github.io"
languageCode = "en-us"
title = "Mijux's blog"
theme = "github-style"

pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Mijux"
  description = "Amateurs hack systems, professionals hack people."
  github = "Mijux"
  twitter = "MijuxDev"
  cyberdefenders = "Mijux"
  dockerhub = "mijuxdev"
#  facebook = ""
#  linkedin = ""
#  instagram = ""
#  tumblr = ""
  email = "mijux-dev@proton.me"
  url = "https://mijux.github.io"
  keywords = "blog, cyber, cybersecurity, cyberdefense, programming, coding, IT, security, portfolio, write-up, analytics"
  rss = true
  lastmod = true
  userStatusEmoji = "🛡️"
  favicon = "/images/avatar.png"
  location = "🤖 Cyberspace"
  
  mamotoserver = "analytics.nogg.ovh"
  mamotoid = "1"

#  enableGitalk = true
#
#  [params.gitalk]
#    clientID = "Your client ID" 
#    clientSecret = "Your client secret" 
#    repo = "repo"
#    owner = "MeiK2333"
#    admin = "MeiK2333"
#    id = "location.pathname"
#    labels = "gitalk"
#    perPage = 15
#    pagerDirection = "last"
#    createIssueManually = true
#    distractionFreeMode = false

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


DefaultContentLanguaga = "en"
[languages]
  [languages.en]
    languageName = "English"
    weight = 1
  [languages.fr]
    languageName = "Français"
    weight = 2
    description = "Les amateurs piratent les systèmes, les professionnels piratent les personnes."
    [languages.fr.params]
      is_french = true