baseURL = "https://mijux.github.io"
languageCode = "en-us"
title = "Mijux's blog"
theme = "github-style"

pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Mijux"
  description = "Amateurs hack systems, professionals hack people."
  github = "Mijux"
#  facebook = ""
  twitter = "MijuxDev"
#  linkedin = ""
#  instagram = ""
#  tumblr = ""
  email = "mijux-dev@proton.me"
  url = "https://mijux.github.io"
  keywords = "blog, cyber, cybersecurity, cyberdefense, programming, coding, IT, security, portfolio, write-up, google analytics"
  rss = true
  lastmod = true
  userStatusEmoji = "🛡️"
  favicon = "/images/github.png"
  location = "🤖 Cyberspace"
#  enableGitalk = true
#
#  [params.gitalk]
#    clientID = "Your client ID" 
#    clientSecret = "Your client secret" 
#    repo = "repo"
#    owner = "MeiK2333"
#    admin = "MeiK2333"
#    id = "location.pathname"
#    labels = "gitalk"
#    perPage = 15
#    pagerDirection = "last"
#    createIssueManually = true
#    distractionFreeMode = false

#  [[params.links]]
#    title = "Link"
#    href = "https://github.com/meik2333"
#  [[params.links]]
#    title = "Link2"
#    href = "https://meik2333.com"
#    icon = "https://meik2333.com/images/avatar.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]


[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


DefaultContentLanguaga = "en"
[languages]
  [languages.en]
    languageName = "English"
    weight = 1
#    [languages.en.params]
#      organizations = "Organizations"
#      search = "Search"
#      overview = "Overview"
#      posts = "Posts"
#      pinned = "Pinned"
#      less = "Less"
#      more = "More"
#      post_activity = "Post activity"
#      created = "Created"
#      modified = "Modified"
#      words = "Words"
#      previous = "Previous"
#      next = "Next"
#      page404 = "Didn’t find anything here!"
  [languages.fr]
    languageName = "Français"
    weight = 2
    description = "Les amateurs piratent les systèmes, les professionnels piratent les personnes."
    [languages.fr.params]
      is_french = true
#      organizations = "Organisations"
#      search = "Rechercher"
#      overview = "Aperçu"
#      posts = "Articles"
#      pinned = "Épinglés"
#      less = "Peu"
#      more = "Beaucoup"
#      post_activity = "Activité de publication"
#      created = "Créé il y a "
#      modified = "Modifié il y a"
#      words = "Mots"
#      previous = "Précédent"
#      next = "Suivant"
#      page404 = "Cette page n'a pas été trouvée"